baseURL: https://www.beep.blog
languageCode: en-GB
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
paginate: 12
params:
  copyright:
    from: 2014
    to: 2023
  author:
    name: Cariad Eccleston
    social:
      url: https://hachyderm.io/@cariad
      label: "@cariad@hachyderm.io"
permalinks:
  /: /:filename
theme: beep
title: beep.blog
