baseURL: https://www.beep.blog/
languageCode: en-GB
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
paginate: 12
params:
  author:
    name: Cariad Eccleston
    social:
      url: https://mastodon.art/@cariad
      label: "@cariad@mastodon.art"
  copyright:
    from: 2014
    to: 2023
  description: A blog by Cariad Eccleston
permalinks:
  /: /:filename
theme: beep
title: beep.blog
