baseURL: https://www.beep.blog/
languageCode: en-GB
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
paginate: 12
params:
  author:
    name: Cariad Eccleston
    social:
      url: https://gamedev.lgbt/@cariad
      label: "@cariad@gamedev.lgbt"
  copyright:
    from: 2014
    to: 2024
  description: A blog by Cariad Eccleston
permalinks:
  /: /:filename

related:
  includeNewer: true
  indices:
    - applyFilter: false
      cardinalityThreshold: 0
      name: keywords
      pattern: ""
      toLower: false
      type: basic
      weight: 100

    - applyFilter: false
      cardinalityThreshold: 0
      name: date
      pattern: ""
      toLower: false
      type: basic
      weight: 10

    - applyFilter: false
      cardinalityThreshold: 0
      name: tags
      pattern: ""
      toLower: false
      type: basic
      weight: 80

  threshold: 80
  toLower: false

theme: beep
title: beep.blog
